// COLEGIO
CREATE TABLE DB2ADB.COLEGIO (id INTEGER NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, sys_start TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN, SYS_END TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW END, create_id timestamp(12) generated always as transaction start id, PERIOD BUSINESS_TIME(start_date, end_date), PERIOD SYSTEM_TIME(SYS_START, SYS_END))

CREATE TABLE DB2ADB.HIST_COLEGIO like DB2ADB.colegio
alter table DB2ADB.colegio add versioning use history table DB2ADB.hist_colegio

CREATE UNIQUE INDEX index_COLEGIO ON Colegio(id, BUSINESS_TIME WITHOUT OVERLAPS)

ALTER TABLE DB2ADB.COLEGIO ADD PRIMARY KEY (id)

// MESA B / S
CREATE TABLE DB2ADB.MESA (id INTEGER NOT NULL, COLEGIO_id INTEGER NOT NULL, LETRA VARCHAR(1) NOT NULL, votos_vacios INTEGER NOT NULL, votos_nulos INTEGER NOT NULL, sys_start TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN, SYS_END TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW END, create_id timestamp(12) generated always as transaction start id, PERIOD SYSTEM_TIME(SYS_START, SYS_END), FOREIGN KEY(COLEGIO_id) REFERENCES DB2ADB.COLEGIO(ID))

create table DB2ADB.hist_mesa like DB2ADB.mesa

alter table DB2ADB.mesa add versioning use history table DB2ADB.hist_mesa

CREATE UNIQUE INDEX index_MESA ON DB2ADB.MESA(id, BUSINESS_TIME WITHOUT OVERLAPS)

ALTER TABLE DB2ADB.MESA ADD PRIMARY KEY (id)

// PARTIDO
CREATE TABLE DB2ADB.PARTIDO (siglas VARCHAR(10) NOT NULL, nombre VARCHAR(45) NOT NULL, nombre_presidente VARCHAR(45) NOT NULL, sys_start TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN, SYS_END TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW END, create_id timestamp(12) generated always as transaction start id, PERIOD SYSTEM_TIME(SYS_START, SYS_END))

create table DB2ADB.hist_partido like DB2ADB.Partido

alter table DB2ADB.partido add versioning use history table DB2ADB.hist_partido

alter table DB2ADB.partido add primary key (siglas)
// VOTANTE S
CREATE TABLE DB2ADB.VOTANTE (ine_pasaporte VARCHAR(45) NOT NULL, nombre VARCHAR(45) NOT NULL, nacimiento DATE NOT NULL, direccion VARCHAR(100) NOT NULL, mesa_id INTEGER NOT NULL, partido_siglas VARCHAR(10) NOT NULL, apoderado BOOLEAN NOT NULL, mexicano BOOLEAN NOT NULL, municipal_federal boolean not NULL, sys_start TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN, SYS_END TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW END, create_id timestamp(12) generated always as transaction start id, PERIOD SYSTEM_TIME(SYS_START, SYS_END), FOREIGN KEY (partido_siglas) REFERENCES DB2ADB.PARTIDO(siglas), FOREIGN KEY (mesa_id) REFERENCES DB2ADB.MESA(id))

create table DB2ADB.hist_votante like DB2ADB.votante

alter table DB2ADB.votante add versioning use history table DB2ADB.hist_votante

alter table DB2ADB.votante add PRIMARY KEY(ine_pasaporte, mesa_id, partido_siglas)

// SUPLENTE B/S
CREATE TABLE DB2ADB.SUPLENTE (SUPLENTE_INE VARCHAR(45) NOT NULL, VOTANTE_MESA_ID INTEGER NOT NULL, VOTANTE_PARTIDO_SIGLAS VARCHAR(10) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, sys_start TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN, SYS_END TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW END, create_id timestamp(12) generated always as transaction start id, PERIOD BUSINESS_TIME(start_date, end_date), period  SYSTEM_TIME(SYS_START, SYS_END), FOREIGN KEY (SUPLENTE_INE, VOTANTE_MESA_ID, VOTANTE_PARTIDO_SIGLAS) REFERENCES DB2ADB.VOTANTE(INE_PASAPORTE, MESA_ID, PARTIDO_SIGLAS))
create table DB2ADB.hist_suplente like DB2ADB.suplente
alter table DB2ADB.suplente add versioning use history table DB2ADB.hist_suplente
CREATE UNIQUE INDEX index_period_SUPLENTE ON DB2ADB.SUPLENTE(SUPLENTE_INE, BUSINESS_TIME WITHOUT OVERLAPS)
alter table DB2ADB.suplente add PRIMARY KEY(SUPLENTE_INE)

// MIEMBRO B /S
CREATE TABLE DB2ADB.MIEMBRO (VOTANTE_INE VARCHAR(45) NOT NULL, VOTANTE_MESA_ID INTEGER NOT NULL, VOTANTE_PARTIDO_SIGLAS VARCHAR(10) NOT NULL, PRESIDENTE_VOCAL BOOLEAN NOT NULL, SUPLENTE_INE VARCHAR(45) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, sys_start TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN, SYS_END TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW END, create_id timestamp(12) generated always as transaction start id, PERIOD BUSINESS_TIME(start_date, end_date), period  SYSTEM_TIME(SYS_START, SYS_END), FOREIGN KEY (VOTANTE_INE, VOTANTE_MESA_ID, VOTANTE_PARTIDO_SIGLAS) REFERENCES DB2ADB.VOTANTE(INE_PASAPORTE, MESA_ID, PARTIDO_SIGLAS), FOREIGN KEY (SUPLENTE_INE) REFERENCES DB2ADB.SUPLENTE(SUPLENTE_INE))
Create table DB2ADB.hist_miembro like DB2ADB.miembro
alter table DB2ADB.miembro add versioning use history table DB2ADB.hist_miembro

CREATE UNIQUE INDEX index_period_MIEMBRO ON DB2ADB.MIEMBRO(VOTANTE_INE, BUSINESS_TIME WITHOUT OVERLAPS)

// LISTA NOMINAL B/S
CREATE TABLE DB2ADB.LISTA_NOMINAL (INE VARCHAR(45) NOT NULL, NOMBRE VARCHAR(45) NOT NULL, PARTIDO_SIGLAS VARCHAR(10) NOT NULL, ORDEN INTEGER NOT NULL, START_DATE TIMESTAMP(6) NOT NULL, END_DATE TIMESTAMP(6) NOT NULL, sys_start TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN, SYS_END TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW END, create_id timestamp(12) generated always as transaction start id, PERIOD BUSINESS_TIME(START_DATE, END_DATE), PERIOD SYSTEM_TIME(SYS_START, SYS_END), FOREIGN KEY (PARTIDO_SIGLAS) REFERENCES DB2ADB.PARTIDO(SIGLAS))
create table DB2ADB.hist_nominal like DB2ADB.lista_nominal
alter table DB2ADB.lista_nominal add versioning use history table DB2ADB.hist_nominal
CREATE UNIQUE INDEX index_nominal ON DB2ADB.lista_nominal(INE, BUSINESS_TIME WITHOUT OVERLAPS)
alter table DB2ADB.lista_nominal add PRIMARY KEY (INE)